### ISSUE TITLE
Why [AllArgsConstructor(MemberType.Property, AccessTypes.Public)] Require the first letter should be capitalized?

### ISSUE THREAD

**Issue by tianmafly** [CollinAlpert/Lombok.NET#12]
[AllArgsConstructor(MemberType.Property, AccessTypes.Public)]
public partial class Test
{
    public string Msg { get; set; } // is OK
    //public string msg { get; set; } // is wrong
}
Why [AllArgsConstructor(MemberType.Property, AccessTypes.Public)] Require the first letter should be capitalized?

**Comment by CollinAlpert** [comment]
Properties in C# are PascalCase by convention, so Lombok.NET expects the first character to be uppercase.

**Comment by tianmafly** [comment]
I think that it is not flexible. 
java the first letter should be lowercase.
It is confounded for people who previously used java.
This people may take a long time to find the problem，and think this is a bug。
thanks

**Comment by CollinAlpert** [comment]
This is not a Java library and it is not designed to work best specifically for Java developers. However, I agree the Source Generator should not generate invalid code, so I will fix this.

**Comment by CollinAlpert** [comment]
The fix is released in v1.2.3.

**Comment by tianmafly** [comment]
It is ok, thanks.
