### ISSUE TITLE
Lombok.Net with .net framework

### ISSUE THREAD

**Issue by Alexander-Gerontas** [CollinAlpert/Lombok.NET#13]
I am developing a .net framework project and your library would help me cleanup a lot of boilerplate in my code. However I think that it only works with .net core projects.

Things I tried: 

- created a .net core console app and added lombok.net with nugget. Annotations [AllArgsConstructor] and [With] are working perfectly.
- created a .net framework console app and imported lombok.net. The annotations are recognized but I cannot create objects using the generated constructor or object copies using [With]

Is the library compatible with .net framework or is it only compatible with .net core? I am using Rider 2022.1.1
Thanks in advance!

**Comment by CollinAlpert** [comment]
I believe using Source Generators in .NET Framework is an unsupported scenario. Can you tell me which .NET Framework version you are using?

**Comment by Alexander-Gerontas** [comment]
Sure, 
Framework version: 4.7.1, 
Language version: C# 10.0

**Comment by CollinAlpert** [comment]
Unfortunately reproducing .NET Framework issues is not really possible for me and it is also not a scenario I want to have to support. I might revisit this issue in the future if I have the means to reproduce it.
