### ISSUE TITLE
Methods created by [Async] "does not implement" interface methods.

### ISSUE THREAD

**Issue by Aytackydln** [CollinAlpert/Lombok.NET#14]
[Async] annotation doesn't pass build check for abstract methods. 
Also, build only fails if you compile from scratch. Incremental build mostly works fine until it doesn't anymore.

![image](https://user-images.githubusercontent.com/11393706/202265719-812c6bc9-18cd-493a-afcd-a61ea7acaa61.png)
![image](https://user-images.githubusercontent.com/11393706/202265740-a01ba1f5-3267-45d3-9ecf-15762d9043f5.png)

**Comment by CollinAlpert** [comment]
That's weird, I can't reproduce the issue, even on a complete rebuild. I've checked the code and everything should work. Can you click the button I have circled in the build window and check if the source generator throws any exception?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/14217185/202280782-dae16404-6a74-4648-a666-2e512d0c8a3d.png">

Any exceptions would show up as warnings during a failed build. Even better would be if you could paste the entire build output.

Another thing you could try is setting `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` in your .csproj file and then checking the `obj/Debug/net7.0/generated/Lombok.NET/Lombok.NET.MethodGenerators.AsyncGenerator` folder and looking at what gets generated.

**Comment by Aytackydln** [comment]
I had this 2 times but can't reproduce now. I will let you know if this happens again

**Comment by CollinAlpert** [comment]
Okay, feel free to reopen when you can reliably reproduce it.
