### ISSUE TITLE
NotifyPropertyChanged inheritance problems

### ISSUE THREAD

**Issue by Aytackydln** [CollinAlpert/Lombok.NET#17]
When inheritance is involved using this attribute is not worth. 

~~1. Sub-class hides higher class's PropertyChanged event.
Using the attribute on multiple class creates bugs because of hidden event~~
Edit: seems this wasn't true.

2. Upper class's  SetFieldAndRaisePropertyChanged is private
Using the attribute on only upper class doesn't work because of private access

My proposal is making SetFieldAndRaisePropertyChanged method protected so that sub-classes can use it

**Comment by CollinAlpert** [comment]
Fixed in version 2.0.0.
