### ISSUE TITLE
The generator dosen't work when the class with same name

### ISSUE THREAD

**Issue by View12138** [CollinAlpert/Lombok.NET#18]
This is a very common scenario when I have different versions of the API and class with the same name but different namespaces, and when Lombok.NET generates the same filename, the generate code will be overwritten or the build fails.

e.g. 
Controllers/v1/CommonController.cs
```csharp
namespace MyWebApi.v1;

[ApiController]
[Route("api/[controller]/[action]")]
[RequiredArgsConstructor]
[Obsolete]
public partial class CommonController : ControllerBase
{
        private readonly ICommonService commonService;
}
```

Controllers/v2/CommonController.cs
```csharp
namespace MyWebApi.v2;

[ApiController]
[Route("api/[controller]/[action]")]
[RequiredArgsConstructor]
public partial class CommonController : ControllerBase
{
        private readonly ICommonService commonService;
}
```

My suggestions：
1. the generated filename use the `AssemblyQualifiedName` for class
2. add property like `[RequiredArgsConstructor(FileName = "V1_CommonController.g.cs")]` in all  Lombok.NET attributes

**Comment by CollinAlpert** [comment]
Fixed in version 2.0.0. The generator now includes the namespace in the file name.
