### ISSUE TITLE
A lot of AsyncMethodMustBeInPartialClassOrStructAnalyzer Warnings

### ISSUE THREAD

**Issue by leonbohmann** [CollinAlpert/Lombok.NET#19]
In my Project I am only using:
```csharp
[NotifyPropertyChanged]
```
and
```csharp
[Property]
```
Attributes. However, when compiling, I receive a lot of these warnings:
```
9>CSC : warning AD0001: Analyzer 'Lombok.NET.Analyzers.AsyncMethodMustBeInPartialClassOrStructAnalyzer' threw an exception of type 'System.TypeAccessException' with message 'Lombok.NET.AsyncAttribute could not be found in compilation.'.
```

Since I am not using any Async Attributes, I don't understand how this error appears? I can still build the project but the build output is filled with these..

**Comment by CollinAlpert** [comment]
That's interesting. Could you give me some more info about your .NET version as well as the library version you are using?
Also, it would be helpful if you could provide a minimal repro (GitHub link or ZIP file) so I can diagnose the issue.

**Comment by leonbohmann** [comment]
After I cleaned all obj and bin folders these now disappeared. Thanks though!
