### ISSUE TITLE
Auto repair code instead of error

### ISSUE THREAD

**Issue by RashSnake** [CollinAlpert/Lombok.NET#35]
When I add a attrbute for a class without partial, Lombok can add keyword 'partial'.
If it can do that, I will don't need to concern about it, learn it.

**Comment by CollinAlpert** [comment]
Unfortunately that is not how C# or Source Generators work. Lombok.NET can only add code, not modify existing code. This is why the best thing it can do is emit an error so you can make the change yourself.
