### ISSUE TITLE
Missing XML comment for publicly visible type or member

### ISSUE THREAD

**Issue by View12138** [CollinAlpert/Lombok.NET#37]
**Describe the bug**
When the documentation file generation feature was enabled (`<GenerateDocumentationFile>True</GenerateDocumentationFile>`) on the project, the generated code caused the compiler to report a warning [Compiler Warning (level 4) CS1591](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591?f1url=%3FappId%3Droslyn%26k%3Dk(CS1591))

**To Reproduce**
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>
</Project >
```

**Screenshots**
![image](https://github.com/CollinAlpert/Lombok.NET/assets/33537441/6b988bf9-fde2-4d78-b0de-aacd569e4e89)
![image](https://github.com/CollinAlpert/Lombok.NET/assets/33537441/e274eb38-af2e-4814-81e3-0d1b950685ba)

**Environment info**
 - .NET version: 8.0
 - Lombok.NET version: 2.3.0

**Comment by CollinAlpert** [comment]
Unfortunately this is a [known issue](https://github.com/dotnet/roslyn/issues/53729) with generated code. The fix is to suppress the error for generated files in your `.editorconfig` like this:

```editorconfig
[*.g.cs]
dotnet_diagnostic.CS1591.severity = none
```

**Comment by CollinAlpert** [comment]
Related to https://github.com/CollinAlpert/Lombok.NET/issues/24.
