### ISSUE TITLE
Async and AsyncOverload

### ISSUE THREAD

**Issue by xafero** [CollinAlpert/Lombok.NET#40]
Does it make sense to generate an async method with "CancellationToken token = default"?

A synchronous one without it and the async one with abort option.

**Comment by CollinAlpert** [comment]
For the `[Async]` attribute it wouldn't make sense, since the implementations leverage `Task.FromResult` and `Task.CompletedTask`; both of which cannot be used with a `CancellationToken`.

Using `[AsyncOverloads]` already generates methods which accept a default `CancellationToken`.
