### ISSUE TITLE
Multiple Constructor Attributes like standard lombok

### ISSUE THREAD

**Issue by WoistdasNiveau** [CollinAlpert/Lombok.NET#43]
I like the approach to specify in the AllArgsConstructor attribute what properties one wants to have included, but for simplicity it would be nice if the AllArgsConstructor would work like the Java Lombok and we had extra Attributes for RequiredArgsConstructor, for the private fields and NoArgsConstructor as well.

**Comment by CollinAlpert** [comment]
I'm not sure what you mean? Lombok.NET has all these attributes. From the [README file](https://github.com/CollinAlpert/Lombok.NET?tab=readme-ov-file#constructors):
> If you only wish to have a constructor generated containing the required fields or properties, Lombok.NET offers the RequiredArgsConstructor attribute. Fields are required if they are readonly, properties are required if they don't have a set accessor.
There is also a NoArgsConstructor attribute which generates an empty constructor.
