### ISSUE TITLE
Make SourceGeneratorAttributes generated by code generator

### ISSUE THREAD

**Issue by frg2089** [CollinAlpert/Lombok.NET#50]
Hi, This is a nice project!
However, Could you please move [SourceGeneratorAttributes](https://github.com/CollinAlpert/Lombok.NET/blob/master/Lombok.NET/SourceGeneratorAttributes.cs) into SourceGenerator?

This will make it purely an analyzer package.
The analyzer is not runtime-limited.
And they will work on .Net Framework 4.0 and .Net Framework 3.5. 

Like this:
```cs
context.RegisterPostInitializationOutput(context => context.AddSource(
    "ToStringAttribute.g.cs",
    $$"""
    namespace Lombok.NET;

    /// <summary>
    /// Tells Lombok.NET to generate a ToString implementation for this type. For enums, a ToText method will be added.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum)]
    internal sealed class ToStringAttribute : Attribute
    {
        // members
    }
    """));
```

<details>

<summary>Work on old platform</summary>

![image](https://github.com/CollinAlpert/Lombok.NET/assets/42184238/939220b9-9e49-4a37-aa3d-d6a8c018c5ed)

</details>

**Comment by CollinAlpert** [comment]
Even if I did that, the package would still target `netstandard2.0`, which would make it unusable for .NET Framework 4.0, correct?

**Comment by frg2089** [comment]
> Even if I did that, the package would still target `netstandard2.0`, which would make it unusable for .NET Framework 4.0, correct?

In fact, a Nuget package reference should be added using something like this.
```csproj
<PackageReference Include="Lombok.NET" Version="2.4.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>analyzers</IncludeAssets>
</PackageReference>
```

This will make them work on .Net Framework 4.0

**Comment by CollinAlpert** [comment]
Sounds like a reasonable request, I will look into it.

**Comment by CollinAlpert** [comment]
I am having some trouble, since Lombok.NET internally uses some of the enums which would then be generated by a source generator. I need to see if I can somehow work around that.

**Comment by frg2089** [comment]
I realize I may have mentioned a difficult feature to implement, the source code generator doesn't seem to have good access to the content generated by the source code generator.

For example, accessing attributes generated by the source code generator via `IncrementalGeneratorInitializationContext.SyntaxProvider.ForAttributeWithMetadataName`.

If we want to provide support for older versions of the .Net Framework, we should publish the attributes in a separate Nuget package and use a multi-target build.

Translated with DeepL.com (free version)
