### ISSUE TITLE
Partial/inherited interfaces miss methods for Decorator

### ISSUE THREAD

**Issue by GrahamTheCoder** [CollinAlpert/Lombok.NET#53]
**Describe the bug**
If an interface is partial. Only the part with `[Decorator]` has decorator methods auto generated.

**To Reproduce**
```csharp
public partial interface IFoo
{
    void Something();
}
[Decorator] //'FooDecorator' does not implement interface member 'IFoo.Something()'
public partial interface IFoo
{
}
```

**Expected behavior**
Generates member even for other part

**Screenshots**

**Environment info**
 - .NET version: 9 preview
 - Lombok.NET version: 2.4.0

**Additional context**
I'm doing this because I used the InterfaceGenerator library to auto generate the interface. So I only added a partial definition of it in order to put the Decorator attribute on it.
No worries if you decide this isn't worth supporting, just thought I would let you know.
Failed workaround: Decorating a new interface inheriting from the generated interface also didn't work

**Comment by CollinAlpert** [comment]
Thank you for the issue, the fix is available in v2.4.1.
