### ISSUE TITLE
With Method's do not return correct type on classes with Generics

### ISSUE THREAD

**Issue by ristogod** [CollinAlpert/Lombok.NET#54]
**Describe the bug**
If I decorate my class `MyClass<T>` with the `[With]` attribute, it will generate methods that do not return `MyClass<T>`, but instead `MyClass`

**To Reproduce**
``` csharp
[With]
public partial class MyClass<T>
{
   public T MyProperty { get; set: }
}
```

**Generates**

``` csharp
partial class MyClass<T>
{
   public MyClass WithMyProperty(T myProperty)
   {
      this.MyProperty = myProperty;

      return this;
   }
}
```

**Expected behavior**
``` csharp
partial class MyClass<T>
{
   public MyClass<T> WithMyProperty(T myProperty)
   {
      this.MyProperty = myProperty;

      return this;
   }
}
```

**Environment info**

.NET version:  8.0
Lombok.NET version: 2.4.0

**Comment by CollinAlpert** [comment]
Thank you for the issue, the fix is available in v2.4.1.
