### ISSUE TITLE
With attribute doesn't respect init

### ISSUE THREAD

**Issue by ristogod** [CollinAlpert/Lombok.NET#57]
**Describe the bug**
If my property uses `init;` it still generates

**To Reproduce**
``` csharp
[With]
public partial class MyClass
{
   public string MyProperty { get; init: }
}
```

**Generates**

``` csharp
partial class MyClass
{
   public MyClass WithMyProperty(string myProperty)
   {
      this.MyProperty = myProperty;

      return this;
   }
}
```

**Expected behavior**
``` csharp
partial class MyClass
{

}
```

**Environment info**

.NET version:  8.0
Lombok.NET version: 2.4.0

**Comment by CollinAlpert** [comment]
Thank you for the issue, the fix is available in v2.4.1.
