### ISSUE TITLE
Is there any option to make the `[Singleton]` attribute return `Lazy<T>` instead of `T`?

### ISSUE THREAD

**Issue by hunter-richardson** [CollinAlpert/Lombok.NET#7]

**Comment by CollinAlpert** [comment]
Not yet, but I'll get on it!

**Comment by CollinAlpert** [comment]
The `[Lazy]` attribute is available in version 1.2.0. See section in [docs](https://github.com/CollinAlpert/Lombok.NET#lazy). Let me know what you think!

**Comment by hunter-richardson** [comment]
Is the "parameterless constructor" requirement also mean "public"? The singleton design pattern usually means the only constructor is private.

**Comment by CollinAlpert** [comment]
No, the constructor can be made private for both `[Singleton]` and `[Lazy]`. I removed the automatic creation of the private constructor for the `Singleton` attribute so developers can add their own constructor code.

**Comment by hunter-richardson** [comment]
Awesome. Thanks!
