### ISSUE TITLE
how to use chain call?

### ISSUE THREAD

**Issue by tianmafly** [CollinAlpert/Lombok.NET#8]
Java Lombok can use chain call by @Accessors(chain = true).
How does Lombok.Net apply this?
thanks

**Comment by CollinAlpert** [comment]
What you're looking for is the [[With]](https://github.com/CollinAlpert/Lombok.NET#with-methods) attribute.

**Comment by CollinAlpert** [comment]
Closing due to lack of further feedback. Feel free to reopen the issue with additional questions/feedback anytime.
